$axure.loadCurrentPage({
  "url":"民俗.html",
  "generationDate":new Date(1432657298729.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7ba6e70d5ded4894aa7e950bfc89dfba",
    "type":"Axure:Page",
    "name":"民俗",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"用例 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"wait",
                "description":"等待10毫秒",
                "waitTime":10},
{
                "action":"setFunction",
                "description":"设置 被选中的 不明 等于 &quot;true&quot;",
                "expr":{
                  "exprType":"block",
                  "subExprs":[]}},
{
                "action":"wait",
                "description":"等待500毫秒",
                "waitTime":500},
{
                "action":"setPanelState",
                "description":"Set Panel to State",
                "panelsToStates":[]}]}]}},
    "diagram":{
      "objects":[{
          "id":"2ceebf986ae04444ba9fa3c28e378edd",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":474.5,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"def9d2ed1bdf4c18815431fdfd085970"},
{
          "id":"cf5c1272f9dc476683b64f8f60ec5dd5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":90},
            "size":{
              "width":360,
              "height":640}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98b016829da64887b67c74bbf3f765aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":90},
                "size":{
                  "width":360,
                  "height":640}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/民俗/u3.png"}}]}},
  "masters":{
    "def9d2ed1bdf4c18815431fdfd085970":{
      "packageId":"def9d2ed1bdf4c18815431fdfd085970",
      "type":"Axure:Master",
      "name":"back",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1a8151aa49684251944aef978bcdde8d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":411,
                "height":830}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"025bd5560eb441e68b331b44461ccfba",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":411,
                    "height":830}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/主页/u1.png"}}]}}},
  "objectPaths":{
    "2ceebf986ae04444ba9fa3c28e378edd":{
      "scriptId":"u0",
      "1a8151aa49684251944aef978bcdde8d":{
        "scriptId":"u1"},
      "025bd5560eb441e68b331b44461ccfba":{
        "scriptId":"u2"}},
    "cf5c1272f9dc476683b64f8f60ec5dd5":{
      "scriptId":"u3"},
    "98b016829da64887b67c74bbf3f765aa":{
      "scriptId":"u4"}}});