$axure.loadCurrentPage({
  "url":"登陆.html",
  "generationDate":new Date(1431580761016.9),
  "isCanvasEnabled":false,
  "variables":["k2",
"k3",
"k4",
"k5",
"login"],
  "page":{
    "packageId":"a11d1f5803dc439e86fd162b4469465d",
    "type":"Axure:Page",
    "name":"登陆",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"用例 1<br> (If value of login等于: &quot;0&quot;)",
            "isNewIfGroup":false,
            "condition":{
              "exprType":"binaryOp",
              "op":"==",
              "leftExpr":{
                "exprType":"fcall",
                "functionName":"GetGlobalVariableValue",
                "arguments":[{
                    "exprType":"globalVariableLiteral",
                    "variableName":"login"}]},
              "rightExpr":{
                "exprType":"stringLiteral",
                "value":"0",
                "stos":[]}},
            "actions":[{
                "action":"fadeWidget",
                "description":"隐藏 注册",
                "objectsToFades":[{
                    "objectPath":["45c3693a8c484aceaf5d4ea647dba6d6"],
                    "fadeInfo":{
                      "fadeType":"hide",
                      "options":{
                        "showType":"none"}}}]}]}]}},
    "diagram":{
      "objects":[{
          "id":"77af0247244e4b6b9f00d5d740ab9c43",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":1280,
              "height":720}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e21487bed07945f2a4022f776beea145",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1280,
                  "height":720}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u0.png"}},
{
          "id":"41712ca3036e49f58a7777ccd61d5871",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x33797979},
            "size":{
              "width":1280,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93a5cbd660504add8713c986838a280d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x33797979},
                "size":{
                  "width":1280,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u2.png"}},
{
          "id":"561facea46574edca75fb70040de01fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Bauhaus 93 Normal', 'Bauhaus 93'",
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF800080,
              "opacity":1},
            "location":{
              "x":20,
              "y":22},
            "size":{
              "width":360,
              "height":52},
            "borderWidth":"1",
            "linePattern":"dashed",
            "outerShadow":{
              "on":true,
              "offsetX":10,
              "offsetY":10,
              "blurRadius":10,
              "color":{
                "r":128,
                "g":0,
                "b":128,
                "a":1}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93f56ac0feed40f6b742ed40d4a4d2bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Bauhaus 93 Normal', 'Bauhaus 93'",
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF800080,
                  "opacity":1},
                "location":{
                  "x":20,
                  "y":22},
                "size":{
                  "width":360,
                  "height":52},
                "borderWidth":"1",
                "linePattern":"dashed",
                "outerShadow":{
                  "on":true,
                  "offsetX":10,
                  "offsetY":10,
                  "blurRadius":10,
                  "color":{
                    "r":128,
                    "g":0,
                    "b":128,
                    "a":1}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc9ea6283be14af4ac4b41229a87913f",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":125},
            "size":{
              "width":10,
              "height":535},
            "borderWidth":"4"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登陆/u6_line.png"}},
{
          "id":"8b0c27985c974e4484637b33c0192e52",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":125},
            "size":{
              "width":10,
              "height":535},
            "borderWidth":"4"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登陆/u6_line.png"}},
{
          "id":"23137debf76545fc9aa6ce865e30db73",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":604,
              "y":240},
            "size":{
              "width":10,
              "height":280}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登陆/u8_line.png"}},
{
          "id":"8497213171b341ffb7b748dceafbd346",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFD9E3EC},
{
                  "color":0xFFD9E3EC},
{
                  "color":0xFFC8DDEE},
{
                  "color":0xFFC8DDEE}]},
            "location":{
              "x":769,
              "y":231},
            "size":{
              "width":350,
              "height":30},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ea04c9dfe694321ac6b549bf2e3e7ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFD9E3EC},
{
                      "color":0xFFD9E3EC},
{
                      "color":0xFFC8DDEE},
{
                      "color":0xFFC8DDEE}]},
                "location":{
                  "x":769,
                  "y":231},
                "size":{
                  "width":350,
                  "height":30},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u9.png"}},
{
          "id":"bafad4bb77564beb9213454b6a207d6b",
          "label":"1",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":871,
              "y":281},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"93d83b3de7694bd19e0ff32c8c3758f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":780,
              "y":284},
            "size":{
              "width":81,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4530a1a982fc4b4296a642ec4289c02b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":780,
                  "y":284},
                "size":{
                  "width":81,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d3a3c9cb739f49c58e8d89479409f676",
          "label":"2",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":871,
              "y":316},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9ae91d0d39444ef3b7b2a3cc07099bcc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":780,
              "y":319},
            "size":{
              "width":81,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad3944d4a684468499781d951ebe85a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":780,
                  "y":319},
                "size":{
                  "width":81,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d362d773aea9431c8f456ac718303522",
          "label":"3",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":871,
              "y":355},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b3f670dbcc5a4026818f75e67280d8a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":780,
              "y":358},
            "size":{
              "width":81,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb2ef8ace1a14f1aa0b9155d3c78e690",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":780,
                  "y":358},
                "size":{
                  "width":81,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3bc59abf4cfa41cfad2f7670d5b83824",
          "label":"4",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":871,
              "y":390},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8edd35f2339446d481a611b3e80cf71f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":780,
              "y":393},
            "size":{
              "width":81,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1dcbb708ac547a4b277f9a34d624770",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":780,
                  "y":393},
                "size":{
                  "width":81,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fe8f036c35d34c0ea1f16776e79ecd2b",
          "label":"5",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":871,
              "y":425},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e76a643495224a7eb114d0e4f468b756",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":780,
              "y":428},
            "size":{
              "width":81,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2023f33324894a8cb20a827929d552f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":780,
                  "y":428},
                "size":{
                  "width":81,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a710defb7714782a581d2c6c440838f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseDown":{
                "outerShadow":{
                  "on":false,
                  "offsetX":0,
                  "offsetY":5,
                  "blurRadius":2,
                  "color":{
                    "r":0,
                    "g":128,
                    "b":0,
                    "a":0.349019607843137}}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF008000},
            "location":{
              "x":780,
              "y":475},
            "size":{
              "width":100,
              "height":35},
            "linePattern":"none",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":5,
              "blurRadius":2,
              "color":{
                "r":0,
                "g":128,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc2e3b391a4a44f6814518eee799be25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseDown":{
                    "outerShadow":{
                      "on":false,
                      "offsetX":0,
                      "offsetY":5,
                      "blurRadius":2,
                      "color":{
                        "r":0,
                        "g":128,
                        "b":0,
                        "a":0.349019607843137}}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF008000},
                "location":{
                  "x":780,
                  "y":475},
                "size":{
                  "width":100,
                  "height":35},
                "linePattern":"none",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":5,
                  "blurRadius":2,
                  "color":{
                    "r":0,
                    "g":128,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 授权与权限管理",
                      "target":{
                        "targetType":"page",
                        "url":"授权与权限管理.html",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"setFunction",
                      "description":"设置 value of login 等于 &quot;1&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"login"},
{
                                "exprType":"stringLiteral",
                                "value":"1",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登陆/u26.png",
            "mouseDown~":"images/登陆/u26_mouseDown.png"}},
{
          "id":"b3ae6a7720464bf2830523a8493b9bf4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseDown":{
                "outerShadow":{
                  "on":false,
                  "offsetX":0,
                  "offsetY":5,
                  "blurRadius":2,
                  "color":{
                    "r":0,
                    "g":128,
                    "b":0,
                    "a":0.349019607843137}}}},
            "location":{
              "x":1019,
              "y":475},
            "size":{
              "width":100,
              "height":35},
            "linePattern":"none",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":5,
              "blurRadius":2,
              "color":{
                "r":0,
                "g":128,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8632b50b17224a7f8e64b4316e5da88a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseDown":{
                    "outerShadow":{
                      "on":false,
                      "offsetX":0,
                      "offsetY":5,
                      "blurRadius":2,
                      "color":{
                        "r":0,
                        "g":128,
                        "b":0,
                        "a":0.349019607843137}}}},
                "location":{
                  "x":1019,
                  "y":475},
                "size":{
                  "width":100,
                  "height":35},
                "linePattern":"none",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":5,
                  "blurRadius":2,
                  "color":{
                    "r":0,
                    "g":128,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 文字于 1 等于 &quot;&quot;, 与<br> 文字于 2 等于 &quot;&quot;, 与<br> 文字于 3 等于 &quot;&quot;, 与<br> 文字于 4 等于 &quot;&quot;, 与<br> 文字于 5 等于 &quot;&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["bafad4bb77564beb9213454b6a207d6b"]},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["d3a3c9cb739f49c58e8d89479409f676"]},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["d362d773aea9431c8f456ac718303522"]},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["3bc59abf4cfa41cfad2f7670d5b83824"]},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["fe8f036c35d34c0ea1f16776e79ecd2b"]},
{
                                "exprType":"stringLiteral",
                                "value":"",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登陆/u28.png",
            "mouseDown~":"images/登陆/u28_mouseDown.png"}},
{
          "id":"45c3693a8c484aceaf5d4ea647dba6d6",
          "label":"注册",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":231},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"577960fcb4104b58bd5cc3d1db0c7c31",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f2e809976ae34314aea9e2a1b23ee4b5",
                  "label":"",
                  "parentDynamicPanel":"45c3693a8c484aceaf5d4ea647dba6d6",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "fill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFFD9E3EC},
{
                          "color":0xFFD9E3EC},
{
                          "color":0xFFC8DDEE},
{
                          "color":0xFFC8DDEE}]},
                    "size":{
                      "width":350,
                      "height":30},
                    "linePattern":"none"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"226fc6dc6c754cd096b1950ffac4a413",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"45c3693a8c484aceaf5d4ea647dba6d6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFD9E3EC},
{
                              "color":0xFFD9E3EC},
{
                              "color":0xFFC8DDEE},
{
                              "color":0xFFC8DDEE}]},
                        "size":{
                          "width":350,
                          "height":30},
                        "linePattern":"none"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登陆/u9.png"}},
{
                  "id":"c4106f5a9d024531b74fd57f4ffab68a",
                  "label":"1",
                  "parentDynamicPanel":"45c3693a8c484aceaf5d4ea647dba6d6",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":102,
                      "y":50},
                    "size":{
                      "width":200,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"1bb6b67cfeab4a239b1de8a3c510838e",
                  "label":"",
                  "parentDynamicPanel":"45c3693a8c484aceaf5d4ea647dba6d6",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":11,
                      "y":53},
                    "size":{
                      "width":81,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9f22d1959bda40d9aa1e15cae5ff9c63",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"45c3693a8c484aceaf5d4ea647dba6d6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":11,
                          "y":53},
                        "size":{
                          "width":81,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e9fc1d491365454f92ec55529f9d5bea",
                  "label":"2",
                  "parentDynamicPanel":"45c3693a8c484aceaf5d4ea647dba6d6",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":102,
                      "y":85},
                    "size":{
                      "width":200,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"8c7507e9175c40259c27a44bff3950ec",
                  "label":"",
                  "parentDynamicPanel":"45c3693a8c484aceaf5d4ea647dba6d6",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":11,
                      "y":88},
                    "size":{
                      "width":81,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b2c00421fcb7438d8b8752ce5c183221",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"45c3693a8c484aceaf5d4ea647dba6d6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":11,
                          "y":88},
                        "size":{
                          "width":81,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a17a427ce57b40d28984a7abd2111862",
                  "label":"",
                  "parentDynamicPanel":"45c3693a8c484aceaf5d4ea647dba6d6",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "stateStyles":{
                      "mouseDown":{
                        "outerShadow":{
                          "on":false,
                          "offsetX":0,
                          "offsetY":5,
                          "blurRadius":2,
                          "color":{
                            "r":0,
                            "g":128,
                            "b":0,
                            "a":0.349019607843137}}}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF008000},
                    "location":{
                      "x":11,
                      "y":244},
                    "size":{
                      "width":100,
                      "height":35},
                    "linePattern":"none",
                    "outerShadow":{
                      "on":true,
                      "offsetX":0,
                      "offsetY":5,
                      "blurRadius":2,
                      "color":{
                        "r":0,
                        "g":128,
                        "b":0,
                        "a":0.349019607843137}}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"368d17e9159b4ec1b2907bdf23379041",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"45c3693a8c484aceaf5d4ea647dba6d6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "stateStyles":{
                          "mouseDown":{
                            "outerShadow":{
                              "on":false,
                              "offsetX":0,
                              "offsetY":5,
                              "blurRadius":2,
                              "color":{
                                "r":0,
                                "g":128,
                                "b":0,
                                "a":0.349019607843137}}}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF008000},
                        "location":{
                          "x":11,
                          "y":244},
                        "size":{
                          "width":100,
                          "height":35},
                        "linePattern":"none",
                        "outerShadow":{
                          "on":true,
                          "offsetX":0,
                          "offsetY":5,
                          "blurRadius":2,
                          "color":{
                            "r":0,
                            "g":128,
                            "b":0,
                            "a":0.349019607843137}}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 主页",
                              "target":{
                                "targetType":"page",
                                "url":"主页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/登陆/u26.png",
                    "mouseDown~":"images/登陆/u26_mouseDown.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "77af0247244e4b6b9f00d5d740ab9c43":{
      "scriptId":"u0"},
    "e21487bed07945f2a4022f776beea145":{
      "scriptId":"u1"},
    "41712ca3036e49f58a7777ccd61d5871":{
      "scriptId":"u2"},
    "93a5cbd660504add8713c986838a280d":{
      "scriptId":"u3"},
    "561facea46574edca75fb70040de01fe":{
      "scriptId":"u4"},
    "93f56ac0feed40f6b742ed40d4a4d2bb":{
      "scriptId":"u5"},
    "bc9ea6283be14af4ac4b41229a87913f":{
      "scriptId":"u6"},
    "8b0c27985c974e4484637b33c0192e52":{
      "scriptId":"u7"},
    "23137debf76545fc9aa6ce865e30db73":{
      "scriptId":"u8"},
    "8497213171b341ffb7b748dceafbd346":{
      "scriptId":"u9"},
    "7ea04c9dfe694321ac6b549bf2e3e7ee":{
      "scriptId":"u10"},
    "bafad4bb77564beb9213454b6a207d6b":{
      "scriptId":"u11"},
    "93d83b3de7694bd19e0ff32c8c3758f7":{
      "scriptId":"u12"},
    "4530a1a982fc4b4296a642ec4289c02b":{
      "scriptId":"u13"},
    "d3a3c9cb739f49c58e8d89479409f676":{
      "scriptId":"u14"},
    "9ae91d0d39444ef3b7b2a3cc07099bcc":{
      "scriptId":"u15"},
    "ad3944d4a684468499781d951ebe85a3":{
      "scriptId":"u16"},
    "d362d773aea9431c8f456ac718303522":{
      "scriptId":"u17"},
    "b3f670dbcc5a4026818f75e67280d8a9":{
      "scriptId":"u18"},
    "eb2ef8ace1a14f1aa0b9155d3c78e690":{
      "scriptId":"u19"},
    "3bc59abf4cfa41cfad2f7670d5b83824":{
      "scriptId":"u20"},
    "8edd35f2339446d481a611b3e80cf71f":{
      "scriptId":"u21"},
    "d1dcbb708ac547a4b277f9a34d624770":{
      "scriptId":"u22"},
    "fe8f036c35d34c0ea1f16776e79ecd2b":{
      "scriptId":"u23"},
    "e76a643495224a7eb114d0e4f468b756":{
      "scriptId":"u24"},
    "2023f33324894a8cb20a827929d552f2":{
      "scriptId":"u25"},
    "4a710defb7714782a581d2c6c440838f":{
      "scriptId":"u26"},
    "cc2e3b391a4a44f6814518eee799be25":{
      "scriptId":"u27"},
    "b3ae6a7720464bf2830523a8493b9bf4":{
      "scriptId":"u28"},
    "8632b50b17224a7f8e64b4316e5da88a":{
      "scriptId":"u29"},
    "45c3693a8c484aceaf5d4ea647dba6d6":{
      "scriptId":"u30"},
    "f2e809976ae34314aea9e2a1b23ee4b5":{
      "scriptId":"u31"},
    "226fc6dc6c754cd096b1950ffac4a413":{
      "scriptId":"u32"},
    "c4106f5a9d024531b74fd57f4ffab68a":{
      "scriptId":"u33"},
    "1bb6b67cfeab4a239b1de8a3c510838e":{
      "scriptId":"u34"},
    "9f22d1959bda40d9aa1e15cae5ff9c63":{
      "scriptId":"u35"},
    "e9fc1d491365454f92ec55529f9d5bea":{
      "scriptId":"u36"},
    "8c7507e9175c40259c27a44bff3950ec":{
      "scriptId":"u37"},
    "b2c00421fcb7438d8b8752ce5c183221":{
      "scriptId":"u38"},
    "a17a427ce57b40d28984a7abd2111862":{
      "scriptId":"u39"},
    "368d17e9159b4ec1b2907bdf23379041":{
      "scriptId":"u40"}}});